### ISSUE TITLE
Some Config Ideas

### ISSUE THREAD

**Issue by juliand665** [darkhax/Modded-Bingo#2]
First of all, I really enjoyed playing with this mod! I'll have to see if I can get a bigger group together soon. There are some things I'd like to be configurable, though:
- The mod currently _consumes_ collectible items upon obtaining them. This can be annoying at times, so I'd appreciate a config option to have them be counted without being consumed.
- The game ends as soon as any team gets bingo, but sometimes it'd be fun to keep playing, either to fight out second place, or to see who can get the full board or something. Again, a config option (or command?) would be nice here, perhaps even also one to make it require multiple completed lines to win.

**Comment by Darkhax** [comment]
For this mod I am trying to make them as data driven as possible, instead of doing configuration stuff. The idea being that users can create and share their own game modes which are customized to how they want to play, or how their server/modpack is designed. 

You can disable the consumption of items by creating a new game mode or overriding the existing one using a json file. https://github.com/Darkhax-Minecraft/Modded-Bingo/blob/1.12.2/src/main/resources/data/bingo/bingo/gamemode/default.json#L46-L48

The ability to add different win conditions is also something I am planning to add.

**Comment by juliand665** [comment]
Ah, interesting. I wish there was an easy way to compose attributes like these, but I guess having it all as part of the game mode makes sense too.

Would different win conditions also encompass having the game continue after someone wins?

**Comment by Darkhax** [comment]
Win conditions are things like requiring 5 in a row, or requiring the full card to be completed. 

Second place is a good idea but the way the mod is now the code doesn't nicely allow for it. I may consider it for the 1.13+ rewrite though.
